language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

git:
  depth: 10

sudo: false

